version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test2
      POSTGRES_USER: account1
      POSTGRES_PASSWORD: account1
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: